name: deploy

on:
  push:

jobs:
  test-job:
    name: TEST -- Build API container image and publish it to GitLab
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta  # used later to refer to the outputs of this step
        with:
          images: |
            registry.gitlab.com/dtgoitia/wipman
          tags: |
            type=ref,event=branch
            type=sha,prefix=,suffix=,format=short

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
