import { generateHash } from "../../domain/hash";
import { Tag, View } from "../../domain/types";

type buildViewArgs = Partial<View>;

export default function buildView({
  id,
  title,
  created,
  updated,
  tags,
  tasks,
}: buildViewArgs): View {
  const view: View = {
    id: id || generateHash(),
    title: title || "autogenerated task title",
    created: created || "2022-09-18T01:00:02+01:00",
    updated: updated || "2022-09-18T07:09:18+01:00",
    tags: tags || new Set<Tag>(),
    tasks: tasks || [],
  };
  return view;
}
